-- Active: 1777281756580@@127.0.0.1@3306@test
CREATE TABLE `tl_user` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `u_id` VARCHAR(64) NOT NULL UNIQUE,

    `name` VARCHAR(128) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,

    `role_ids` JSON NULL,

    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,

    INDEX idx_name (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `tl_role` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `u_id` VARCHAR(64) NOT NULL UNIQUE,

    `name` VARCHAR(128) NOT NULL UNIQUE,

    `permission_ids` JSON NULL,

    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,

    INDEX idx_name (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `tl_permission` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `u_id` VARCHAR(64) NOT NULL UNIQUE,

    `code` VARCHAR(128) NOT NULL UNIQUE,

    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,

    INDEX idx_code (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;